header:
  version: 10

distro: mld

env: 
  USER: none

target:
  - mld-image-base

repos:
  meta-mld:
    url: https://gitlab.com/MLD-6/meta-mld.git
    refspec: honister 
    layers:
      meta:

  poky:
    url: https://git.yoctoproject.org/git/poky
    refspec: honister
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    refspec: honister
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-initramfs:
      meta-multimedia:

  meta-qt5:
    url: https://github.com/meta-qt5/meta-qt5.git
    refspec: honister
    
bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  autoinc_version: |
    INHERIT += "buildhistory"
    BUILDHISTORY_COMMIT = "1"
    PRSERV_HOST = "localhost:0"

  shared_cache: |
    DL_DIR ?= "/home/share/downloads"
    SSTATE_DIR ?= "/home/share/sstate-cache"

  diskmon: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        ABORT,${TMPDIR},100M,1K \
        ABORT,${DL_DIR},100M,1K \
        ABORT,${SSTATE_DIR},100M,1K \
        ABORT,/tmp,10M,1K"

  bootloader: |
    LABELS = "normal verbose"
    SYSLINUX_SERIAL = ""
    SYSLINUX_SPLASH = "${TOPDIR}/../meta-mld/meta/files/splash.png"
    SYSLINUX_OPTS = "menu RESOLUTION 800 600;menu WIDTH 28;menu MARGIN 1;menu ROWS 6;menu HSHIFT 35;menu VSHIFT 19;menu TABMSGROW -1;menu CMDLINEROW -1;menu TIMEOUTROW 20;menu CLEAR;menu HIDDEN;menu color screen * #00ffffff #00ffffff none;menu color border * #00ffffff #00ffffff none;menu color title * #00ffffff #00ffffff none;menu color unsel * #88ffffff #00ffffff none;menu color sel * #ffffffff #ffc00000 none;menu color disabled * #09ffffff #00ffffff none;menu color tabmsg * #09ffffff #00ffffff none;menu color cmdline * #88ffffff #00ffffff none;menu color timeout * #09ffffff #00ffffff none;menu color timeout_msg * #09ffffff #00ffffff none"
    SYSTEMD_BOOT_TIMEOUT = "5"
    EFI_PROVIDER = "systemd-boot"

  bootoptions: |
    APPEND += "net.ifnames=0"
    APPEND:append:normal += "vt.global_cursor_default=0 splash vga=current quiet"
    #APPEND:append:normal += "loglevel=3 rd.systemd.show_status=auto rd.udev.log_level=3"

  filesystems: |
    INITRAMFS_FSTYPES = "cpio.lzma"
    LIVE_ROOTFS_TYPE = "squashfs"

  systemd: |
    VIRTUAL-RUNTIME_init_manager = "systemd"
    DISTRO_FEATURES += "systemd"
    DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
    #VIRTUAL-RUNTIME_initscripts = "" # remove sysvinit completely
    #VIRTUAL-RUNTIME_initscripts = "systemd-compat-units" # enable sysvinit fallback

  plymouth: |
    DISTRO_FEATURES += "plymouth"
    SPLASH = "plymouth"
    EXTRA_IMAGE_FEATURES += "splash"

  package-management: |
    PACKAGE_CLASSES = "package_deb"
    EXTRA_IMAGE_FEATURES += "package-management"
    PACKAGE_FEED_URIS = "http://mld6.minidvblinux.de/${USER}/deb"

  login: |
    #EXTRA_IMAGE_FEATURES += "empty-root-password allow-empty-password"
    EXTRA_IMAGE_FEATURES += "debug-tweaks"

  locale: |
    # PACKAGE_NO_LOCALE = "1" # dies fasst alle Sprachen in einem Paket zusammen und wird in poky/meta/classes/package.bbclass ausgewertet. Hier könnte auch eine automatische Abhängigkeit zu den IMAGE_LINGUAS sprachen in alle Pakete eingebaut werden. Z.B.: d.setVar('RRECOMMENDS', (d.getVar('RRECOMMENDS') or "") + ' ' + pn + '-locale-de-de')
    # GLIBC_GENERATE_LOCALES = "en_GB.UTF-8 de_DE.UTF-8"
    IMAGE_LINGUAS = "en-gb de-de"
    CORE_IMAGE_EXTRA_INSTALL += "tzdata"
    DEFAULT_TIMEZONE = "Europe/Berlin"

  other: |
    CONF_VERSION = "1"
    LICENSE_FLAGS_WHITELIST = "commercial"
    SDKMACHINE = "x86_64"
    hostname:pn-base-files = "MLD"
    SERIAL_CONSOLES = ""
    KERNEL_SPLIT_MODULES = "0"

  features: |
    CORE_IMAGE_EXTRA_INSTALL += "kernel-modules"
    IMAGE_FEATURES += "ssh-server-openssh"
    CORE_IMAGE_EXTRA_INSTALL += "ca-certificates"
    CORE_IMAGE_EXTRA_INSTALL += "xf86-video-fbdev"
    DISTRO_FEATURES += "x11"
    #DISTRO_FEATURES += "opengl"
    #DISTRO_FEATURES += "vulkan"
    #DISTRO_FEATURES += "directfb"
    #DISTRO_FEATURES += "kms"
