services:
  mld6:
    container_name: MLD-6
    hostname: MLD-6
    image: mld/dev:6
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    userns_mode: "keep-id"
    ports:
      - "2200:22"
      - "8000:80"
    volumes:
      - type: bind
        source: .
        target: /home/mld/mld-dev
    restart: always
